---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  # Установим 4 реплики по ТЗ
  replicas: 4
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      # Используем anti-affinity для распределения подов по разным нодам
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - web-app
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: web-app
        image: your-web-app-image:tag
        resources:
          requests:
            # Запрашиваем минимальные ресурсы по ТЗ
            cpu: 100m
            memory: 128Mi
          limits:
            # Далее устанавим лимиты выше, так как при старте происходит большое потребление
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          # Учитываем время инициализации приложения
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app
  minReplicas: 2  # Минимальное количество подов для обеспечения отказоустойчивости
  maxReplicas: 6  # Максимальное количество подов, учитывая пиковую нагрузку
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      # Настраиваем более медленное масштабирование вниз для стабильности
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max